#!/usr/bin/env python3

# Standard library imports
import os
from argparse import Namespace

# Custom library imports
import dependencies.args as args
import dependencies.cli as cli
import dependencies.healthcheck as healthcheck
import dependencies.module as modules
from dependencies.modules.base import BaseModule

# Type hinting imports
from dependencies.target import Target


def main():
    # Clear the screen
    print(cli.clear, end="")

    # Display sick-ass banner
    cli.banner()

    ############################
    ### START INITIALIZATION ###
    ############################
    cli.info("Initializing probe...", end="")

    # Parse command-line arguments, load target, and load modules
    parsed_args: Namespace = args.parse_args()
    target: Target = Target(parsed_args.target)
    active_modules: list[type[BaseModule]] = modules.load_all()

    cli.success()

    # Summarize the target information and loaded modules
    target.summary()
    modules.summary(active_modules)

    cli.info(f"Initialization {cli.green}complete!{cli.reset}", end="\n\n")

    ##########################
    ### START HEALTH CHECK ###
    ##########################
    # Grab terminal width
    width = os.get_terminal_size().columns if os.isatty(1) else 80
    print(f"{cli.green}{'─' * width}{cli.reset}\n")

    # Run health check
    cli.info("Running health check against target.")
    healthy = healthcheck.check_health(target)
    if not healthy:
        cli.continue_prompt(
            "Health check failed. Do you want to continue anyway?", default="y"
        )
    print()

    #######################
    ### RUN ALL MODULES ###
    #######################
    cli.info("Running modules against target.")
    results: dict[str, list[str]] = modules.run_all(target)

    cli.end_msg()


if __name__ == "__main__":
    main()
