#!/usr/bin/env python3

import dependencies.args as args
import dependencies.healthcheck as healthcheck
import dependencies.cli as cli

def main():
    # Parse command-line arguments
    parsed_args = args.parse_args()
    print(f"Selected target: {cli.bold}{parsed_args.target}{cli.normal}")

    healthy = healthcheck.check_health(parsed_args.target)
    if healthy: 
        print(f"\t{cli.success}{cli.bold} Target is healthy{cli.normal}")
    else:
        print(f"\t{cli.error}{cli.bold} Target is not healthy{cli.normal}")

if __name__ == "__main__":
    main()